model_name: "roberta-base"
num_labels: 9
training_args:
  output_dir: "ner_checkpoints"
  evaluation_strategy: "steps"
  learning_rate: !!float 2e-5
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  num_train_epochs: 2
  weight_decay: 0.01
  logging_dir: "./logs"
  report_to: "tensorboard"
  logging_steps: 100
